definitions:
  main.User:
    properties:
      name:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
paths:
  /users:
    get:
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.User'
            type: array
      summary: Get list of users
swagger: "2.0"
